require: rubocop-sorbet

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

Sorbet/FalseSigil:
  Exclude:
    - spec/*.rb

Sorbet/ValidSigil:
  Exclude:
    - spec/*.rb

# Conflicts with sorbet
Style/AccessorGrouping:
  Enabled: false
