# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: strict

class ::Rake::DSL; end
class ::Rake::TaskLib; end
